### PR TITLE
Bump version to 1.16.3

### PR DESCRIPTION
**Pull request by mihawk90**

### CODE REVIEW

**Comment by djotaku** [comment]
good catch. Just noticed it myself yesterday and hadn't updated yet. Will now merge.

**Comment by mihawk90** [comment]
Since this was a one-liner change I submitted this before actually letting the compile run.
I am wondering if it works for you? I ran it with the F33 base, and it ran fine packing the .src.rpm, but it won't compile the binary version. I'm getting this:

```
RPM build errors:
Finish: rpmbuild makemkv-1.16.3-1.fc33.src.rpm
Finish: build phase for makemkv-1.16.3-1.fc33.src.rpm
ERROR: Exception(/var/lib/mock/fedora-33-x86_64/result/makemkv-1.16.3-1.fc33.src.rpm) Config(fedora-33-x86_64) 1 minutes 27 seconds
INFO: Results and/or logs in: /var/lib/mock/fedora-33-x86_64/result
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 7121b9777bfd48619dfd54a6d6990e81 -D /var/lib/mock/fedora-33-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.62trbu7e:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/originals/makemkv.spec
```

The log doesn't tell me much unfortunately, so I'm wondering if it's an issue on my system or with the build.
[build.log](https://github.com/djotaku/Makemkv-Spec-for-Fedora/files/6308861/build.log)

**Comment by djotaku** [comment]
running it now....

**Comment by djotaku** [comment]
My errors look just like yours

**Comment by djotaku** [comment]
grab my latest update - seems to work now

**Comment by mihawk90** [comment]
Yup, worked fine for me as well! Thanks :)

**Pull request merged**
